// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msvndcjxykfafwcwgcqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdm5kY2p4eWtmYWZ3Y3dnY3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMzY4MjIsImV4cCI6MjA4NzYxMjgyMn0.tuYmf5uInmRYVMx7E1l2cQgQCInym5B_oX5mSJtg82U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});